---
- name: config| create settings directory
  become: true
  file:
    path: '~{{ item.username }}/.config/Code/User'
    state: directory
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 'u=rwx,go='
  with_items: '{{ users }}'

- name: config| write settings
  become: true
  template:
    src: settings.json.j2
    dest: '~{{ item.username }}/.config/Code/User/settings.json'
    force: false
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 'u=rw,go='
  with_items: '{{ users }}'
  when:
    - item.vscode_settings is defined
    - item.vscode_settings not in ({}, '', None, omit)
