---
- name: config| create settings directory for {{ user.username }}
  become: true
  file:
    path: '~{{ user.username }}/.var/app/com.visualstudio.code/config/Code/User'
    state: directory
    owner: '{{ user.username }}'
    group: '{{ user.username }}'
    mode: 'u=rwx,go='

- name: config| write settings for {{ user.username }}
  become: true
  template:
    src: settings.json.j2
    dest: '~{{ item.username }}/.var/app/com.visualstudio.code/config/Code/Usersettings.json'
    force: false
    owner: '{{ user.username }}'
    group: '{{ user.username }}'
    mode: 'u=rw,go='
