---
- name: config| create settings directory
  become: yes
  file:
    path: '~{{ item.username }}/.config/Code/User'
    state: directory
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 'u=rwx,go='
  with_items: '{{ users }}'

- name: config| write settings
  become: yes
  template:
    src: settings.json.j2
    dest: '~{{ item.username }}/.config/Code/User/settings.json'
    force: no
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 'u=rw,go='
  with_items: '{{ users }}'
  when: item.vscode_settings is defined and 
        item.vscode_settings not in ({}, '', None, omit)