---
- name: do these tasks for RedHat-y systems [{{ user.username }}]
  block:
    - name: extensions| install extension cli dependencies for Fedora
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - libX11-xcb
  when: ansible_distribution == "Fedora"

- name: do these tasks for Debian-y systems [{{ user.username }}]
  block:
    - name: extensions| install extension cli dependencies for Debian
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - gconf2
        - libasound2
        - libgtk2.0-0
        - libxss1
  when: ansible_os_family == "Debian"

# - name: extensions| create config directories for users
#   become: true
#   file:
#     path: "~{{ user.username }}/.config"
#     state: directory
#     owner: "{{ user.username }}"
#     group: "{{ user.username }}"
#     mode: 'u=rwx,go=r'

# - name: extensions| create Visual Studio Code directories for users
#   become: true
#   file:
#     path: "~{{ user.username }}/.config/Code/User"
#     state: directory
#     owner: "{{ user.username }}"
#     group: "{{ user.username }}"
#     mode: 'u=rwx,go='

- name: extensions| install extensions for {{ user.username }}
  become: true
  become_user: "{{ user.username }}"
  shell: echo "code --install-extension {{ item }}" | flatpak run --command=bash com.visualstudio.code
  with_items:
    - "{{ user.vscode_extensions }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
