---
# this will be installed via flatpak, so config flatpak repo and install

- name: install| install the flatpak package (OS)
  become: true
  package:
    name: flatpak
    state: present

- name: install| enable the flatpak repository
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  register: output
  failed_when: "'already exists' not in output.stderr"

- name: install| install flatpak
  become: true
  flatpak:
    name: com.visualstudio.code
